# Generated by Django 4.1.3 on 2023-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=''),
        ),
    ]
