# Generated by Django 4.1.3 on 2023-02-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_menu_image_alter_menu_detail_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('message', models.TextField(default='')),
                ('rating', models.IntegerField(default='')),
                ('profile', models.URLField(default='')),
            ],
        ),
    ]
