# Generated by Django 4.1.3 on 2023-02-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('phone', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('date', models.DateTimeField(default='')),
            ],
        ),
    ]
